- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    access_key: "AKIAYIJQ6PVHQWLUQAX3"
    secret_key: "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"
    region: "ap-south-1"
    ami_id: "ami-0b02eacf129bfac4e"
    instance_type: "t2.micro"
    key_name: "ansible_tower"
    security_group: "testec2-security-grp"
    subnet_id: "subnet-0135049ae6777d849"

  tasks:
    - name: Launch EC2 Instance
      ec2:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        region: "{{ region }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        group_id: "{{ security_group }}"
        subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
        wait: true
        count: 1
      register: ec2_instance

    - name: Add newly created EC2 instance to hosts group
      add_host:
        hostname: "{{ ec2_instance.instances[0].public_ip }}"
        groups: ec2_instances
