- name: Ansible test
  hosts: all
  tasks:
  - name: launching AWS instance using Ansible
    ec2:
       key_name: ansible_tower
       instance_type: t2.micro
       image: ami-06c2ec1ceac22e8d6
       region: ap-south-1
       wait: yes
       group: Ansible
       count: 1
       vpc_subnet_id: subnet-0591837b02414148d
       assign_public_ip: yes
       aws_access_key: AKIAYIJQ6PVHYL7JHUQA
       aws_secret_key: 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       
