- name: Ansible test
  hosts: localhost
  tasks:
  - name: launching AWS instance using Ansible
    ec2:
       key_name: ansible_tower
       instance_type: t2.micro
       image: ami-06c2ec1ceac22e8d6
       region: ap-south-1
       wait: yes
       group: Ansible
       count: 1
       vpc_subnet_id: default
       assign_public_ip: yes
       aws_access_key: AKIAQ5RX5OIEEB6BYW2H
       aws_secret_key: 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       
